name: Snyk Source Scan (No requirements.txt)

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Snyk on Python source code
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file=vulnerable_app.py --project-name=python-code-review --severity-threshold=low
