name: Security Scan

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ---------- Bandit Static Code Analysis ----------
      - name: Run Bandit (Python static analysis)
        uses: tj-actions/bandit@v5
        with:
          path: "."  # Scans all Python files

      # ---------- Snyk Dependency Scan ----------
      - name: Snyk scan for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test  # This will scan requirements.txt
